# Generated by Django 5.1.6 on 2025-03-03 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('checkin_id', models.AutoField(primary_key=True, serialize=False)),
                ('checkin_time', models.DateTimeField(blank=True, null=True)),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CheckIn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(db_column='class_ID', primary_key=True, serialize=False)),
                ('class_name', models.TextField()),
                ('instructor', models.TextField()),
                ('semseter', models.TextField()),
            ],
            options={
                'db_table': 'Class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.TextField()),
                ('lname', models.TextField()),
                ('password', models.TextField()),
                ('username', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'Faculty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('written_review', models.TextField()),
            ],
            options={
                'db_table': 'Reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.TextField()),
                ('week', models.TextField()),
                ('month', models.TextField()),
                ('year', models.IntegerField()),
                ('semester', models.TextField()),
            ],
            options={
                'db_table': 'Schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.TextField()),
                ('lname', models.TextField()),
                ('username', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('western_id', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'Students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('tutor_id', models.AutoField(db_column='tutor_ID', primary_key=True, serialize=False)),
                ('fname', models.TextField(unique=True)),
                ('lname', models.TextField(unique=True)),
                ('western_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Tutor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentCheckin',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='monitor.students')),
                ('checkin_time', models.DateTimeField(blank=True, null=True)),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Student_CheckIN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TutorReviews',
            fields=[
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='monitor.tutor')),
                ('date_of_reveiw', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Tutor_Reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TutorSchedule',
            fields=[
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='monitor.tutor')),
            ],
            options={
                'db_table': 'Tutor_Schedule',
                'managed': False,
            },
        ),
    ]
