# Generated by Django 4.2.18 on 2025-03-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="classes",
            field=models.ManyToManyField(related_name="students", to="monitor.class"),
        ),
    ]
