# Generated by Django 5.1.6 on 2025-03-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_remove_students_password_remove_students_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_number',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
