# Generated by Django 4.2.18 on 2025-03-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0004_class_class_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="western_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
