# Generated by Django 5.1.6 on 2025-04-20 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0005_alter_students_western_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="tutor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="monitor.tutor",
            ),
        ),
    ]
