# Generated by Django 5.1.6 on 2025-04-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0006_alter_reviews_tutor"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
