# Generated by Django 5.1.6 on 2025-04-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0007_reviews_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
