# Generated by Django 5.1.6 on 2025-04-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_alter_tutorreviews_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.CharField(default=None, max_length=16),
            preserve_default=False,
        ),
    ]
