# Generated by Django 4.2.23 on 2025-08-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_class_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='classes',
            field=models.ManyToManyField(related_name='tutors', to='monitor.class'),
        ),
    ]
