# Generated by Django 4.2.23 on 2025-08-27 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_tutor_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='class_reviewed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='monitor.class'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='subject_reviewed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
