# Generated by Django 4.2.23 on 2025-08-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_reviews_class_reviewed_reviews_subject_reviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='smtp.office365.com', max_length=100)),
                ('email_port', models.IntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_host_user', models.EmailField(default='jeremiah.cramer@western.edu', max_length=254)),
                ('email_host_password', models.CharField(help_text='App password for 2FA accounts', max_length=255)),
                ('admin_email', models.EmailField(default='jeremiah.cramer@western.edu', max_length=254)),
                ('from_email', models.EmailField(default='jeremiah.cramer@western.edu', max_length=254)),
                ('enable_error_notifications', models.BooleanField(default=True)),
                ('enable_csv_email_exports', models.BooleanField(default=True)),
                ('enable_weekly_summaries', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
                'db_table': 'EmailSettings',
                'managed': True,
            },
        ),
    ]
